name: identity_firebase_twitter
description: Twitter SSO by Firebase for Identity package
version: 0.2.2
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase-twitter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.2.0
  identity: ^0.2.0
  identity_firebase: ^0.2.0
  firebase_auth: ^0.15.3
  flutter_twitter: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/twitter.png
